package com.bugflow.service.ai;

public interface AiProvider {
    /**
     * Generates a text completion based on the given prompt.
     * @param prompt the text prompt sent to the LLM.
     * @return the text generated by the model (or JSON representation).
     */
    String generateText(String prompt);
}
